### ISSUE TITLE
It doesn't build anymore

### ISSUE THREAD

**Issue by stalek71** [ecliptical/tokio-postgres-rustls-rds-demo#1]
It's not up to date. 
I was looking for a way to setup connection to postgres based on tokio-postgres and  tokio-postgres-rustls 
using latest lib versions but it seems to be very outdated.
To be honest I'm very new to rust so I can be wrong and maybe it just needs a few fixes only...

**Comment by pnehrer** [comment]
Thanks for bringing this to my attention! I updated the dependencies and code to the latest versions. Please give it another try.
